//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.19 at 05:03:30 PM EET 
//


package ua.com.smiddle.proxy.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.com.smiddle.proxy.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.com.smiddle.proxy.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SessionInfo }
     * 
     */
    public SessionInfo createSessionInfo() {
        return new SessionInfo();
    }

    /**
     * Create an instance of {@link RecSearchRequest }
     * 
     */
    public RecSearchRequest createRecSearchRequest() {
        return new RecSearchRequest();
    }

    /**
     * Create an instance of {@link RecStartRequest }
     * 
     */
    public RecStartRequest createRecStartRequest() {
        return new RecStartRequest();
    }

    /**
     * Create an instance of {@link RecGetInfoResponse }
     * 
     */
    public RecGetInfoResponse createRecGetInfoResponse() {
        return new RecGetInfoResponse();
    }

    /**
     * Create an instance of {@link RecStartResponse }
     * 
     */
    public RecStartResponse createRecStartResponse() {
        return new RecStartResponse();
    }

    /**
     * Create an instance of {@link RecGetInfoRequest }
     * 
     */
    public RecGetInfoRequest createRecGetInfoRequest() {
        return new RecGetInfoRequest();
    }

    /**
     * Create an instance of {@link TrackInfoVO }
     * 
     */
    public TrackInfoVO createTrackInfoVO() {
        return new TrackInfoVO();
    }

    /**
     * Create an instance of {@link SessionInfoList }
     * 
     */
    public SessionInfoList createSessionInfoList() {
        return new SessionInfoList();
    }

    /**
     * Create an instance of {@link RecSearchResponse }
     * 
     */
    public RecSearchResponse createRecSearchResponse() {
        return new RecSearchResponse();
    }

    /**
     * Create an instance of {@link SessionInfo.Track }
     * 
     */
    public SessionInfo.Track createSessionInfoTrack() {
        return new SessionInfo.Track();
    }

}
