//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.08 at 02:08:29 PM EET 
//


package ua.com.smiddle.proxy.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userLogin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumberB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateFromDuration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="durationFrom" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="durationTo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userLogin",
    "phoneNumberA",
    "phoneNumberB",
    "dateFrom",
    "dateFromDuration",
    "durationFrom",
    "durationTo"
})
@XmlRootElement(name = "RecSearchRequest")
public class RecSearchRequest
    implements ToString
{

    @XmlElement(required = true)
    protected String userLogin;
    @XmlElement(required = true)
    protected String phoneNumberA;
    @XmlElement(required = true)
    protected String phoneNumberB;
    @XmlElement(required = true)
    protected String dateFrom;
    protected int dateFromDuration;
    protected int durationFrom;
    protected int durationTo;

    /**
     * Gets the value of the userLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * Sets the value of the userLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLogin(String value) {
        this.userLogin = value;
    }

    /**
     * Gets the value of the phoneNumberA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumberA() {
        return phoneNumberA;
    }

    /**
     * Sets the value of the phoneNumberA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumberA(String value) {
        this.phoneNumberA = value;
    }

    /**
     * Gets the value of the phoneNumberB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumberB() {
        return phoneNumberB;
    }

    /**
     * Sets the value of the phoneNumberB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumberB(String value) {
        this.phoneNumberB = value;
    }

    /**
     * Gets the value of the dateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFrom() {
        return dateFrom;
    }

    /**
     * Sets the value of the dateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFrom(String value) {
        this.dateFrom = value;
    }

    /**
     * Gets the value of the dateFromDuration property.
     * 
     */
    public int getDateFromDuration() {
        return dateFromDuration;
    }

    /**
     * Sets the value of the dateFromDuration property.
     * 
     */
    public void setDateFromDuration(int value) {
        this.dateFromDuration = value;
    }

    /**
     * Gets the value of the durationFrom property.
     * 
     */
    public int getDurationFrom() {
        return durationFrom;
    }

    /**
     * Sets the value of the durationFrom property.
     * 
     */
    public void setDurationFrom(int value) {
        this.durationFrom = value;
    }

    /**
     * Gets the value of the durationTo property.
     * 
     */
    public int getDurationTo() {
        return durationTo;
    }

    /**
     * Sets the value of the durationTo property.
     * 
     */
    public void setDurationTo(int value) {
        this.durationTo = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theUserLogin;
            theUserLogin = this.getUserLogin();
            strategy.appendField(locator, this, "userLogin", buffer, theUserLogin);
        }
        {
            String thePhoneNumberA;
            thePhoneNumberA = this.getPhoneNumberA();
            strategy.appendField(locator, this, "phoneNumberA", buffer, thePhoneNumberA);
        }
        {
            String thePhoneNumberB;
            thePhoneNumberB = this.getPhoneNumberB();
            strategy.appendField(locator, this, "phoneNumberB", buffer, thePhoneNumberB);
        }
        {
            String theDateFrom;
            theDateFrom = this.getDateFrom();
            strategy.appendField(locator, this, "dateFrom", buffer, theDateFrom);
        }
        {
            int theDateFromDuration;
            theDateFromDuration = this.getDateFromDuration();
            strategy.appendField(locator, this, "dateFromDuration", buffer, theDateFromDuration);
        }
        {
            int theDurationFrom;
            theDurationFrom = this.getDurationFrom();
            strategy.appendField(locator, this, "durationFrom", buffer, theDurationFrom);
        }
        {
            int theDurationTo;
            theDurationTo = this.getDurationTo();
            strategy.appendField(locator, this, "durationTo", buffer, theDurationTo);
        }
        return buffer;
    }

}
