//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.19 at 01:52:29 PM EET 
//


package ua.com.smiddle.proxy.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CucmCallID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserLogin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PhoneDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestinationDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cucmCallID",
    "userLogin",
    "phoneDN",
    "destinationDN"
})
@XmlRootElement(name = "RecStartRequest")
public class RecStartRequest {

    @XmlElement(name = "CucmCallID", required = true)
    protected String cucmCallID;
    @XmlElement(name = "UserLogin", required = true)
    protected String userLogin;
    @XmlElement(name = "PhoneDN", required = true)
    protected String phoneDN;
    @XmlElement(name = "DestinationDN", required = true)
    protected String destinationDN;

    /**
     * Gets the value of the cucmCallID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCucmCallID() {
        return cucmCallID;
    }

    /**
     * Sets the value of the cucmCallID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCucmCallID(String value) {
        this.cucmCallID = value;
    }

    /**
     * Gets the value of the userLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * Sets the value of the userLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLogin(String value) {
        this.userLogin = value;
    }

    /**
     * Gets the value of the phoneDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneDN() {
        return phoneDN;
    }

    /**
     * Sets the value of the phoneDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneDN(String value) {
        this.phoneDN = value;
    }

    /**
     * Gets the value of the destinationDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationDN() {
        return destinationDN;
    }

    /**
     * Sets the value of the destinationDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationDN(String value) {
        this.destinationDN = value;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("RecStartRequest{");
        sb.append("cucmCallID='").append(cucmCallID).append('\'');
        sb.append(", userLogin='").append(userLogin).append('\'');
        sb.append(", phoneDN='").append(phoneDN).append('\'');
        sb.append(", destinationDN='").append(destinationDN).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
