//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 12:27:54 PM EET 
//


package ua.com.smiddle.proxy.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CucmCallID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UserLogin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PhoneDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestinationDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cucmCallID",
    "userLogin",
    "phoneDN",
    "destinationDN"
})
@XmlRootElement(name = "RecStartRequest")
public class RecStartRequest
    implements ToString
{

    @XmlElement(name = "CucmCallID", required = true)
    protected String cucmCallID;
    @XmlElement(name = "UserLogin", required = true)
    protected String userLogin;
    @XmlElement(name = "PhoneDN", required = true)
    protected String phoneDN;
    @XmlElement(name = "DestinationDN", required = true)
    protected String destinationDN;

    /**
     * Gets the value of the cucmCallID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCucmCallID() {
        return cucmCallID;
    }

    /**
     * Sets the value of the cucmCallID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCucmCallID(String value) {
        this.cucmCallID = value;
    }

    /**
     * Gets the value of the userLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * Sets the value of the userLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLogin(String value) {
        this.userLogin = value;
    }

    /**
     * Gets the value of the phoneDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneDN() {
        return phoneDN;
    }

    /**
     * Sets the value of the phoneDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneDN(String value) {
        this.phoneDN = value;
    }

    /**
     * Gets the value of the destinationDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationDN() {
        return destinationDN;
    }

    /**
     * Sets the value of the destinationDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationDN(String value) {
        this.destinationDN = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theCucmCallID;
            theCucmCallID = this.getCucmCallID();
            strategy.appendField(locator, this, "cucmCallID", buffer, theCucmCallID);
        }
        {
            String theUserLogin;
            theUserLogin = this.getUserLogin();
            strategy.appendField(locator, this, "userLogin", buffer, theUserLogin);
        }
        {
            String thePhoneDN;
            thePhoneDN = this.getPhoneDN();
            strategy.appendField(locator, this, "phoneDN", buffer, thePhoneDN);
        }
        {
            String theDestinationDN;
            theDestinationDN = this.getDestinationDN();
            strategy.appendField(locator, this, "destinationDN", buffer, theDestinationDN);
        }
        return buffer;
    }

}
